// web/shared/components/dialog-clients.tsx
import { useRef, useImperativeHandle } from 'preact/hooks';
import { forwardRef } from 'preact/compat';
import { Button, Modal, Table } from 'react-daisyui';

import { type Session, deleteSession } from '../api';
import { formatBitrate, formatTime } from '../utils';

interface Props {
    id: string
    sessions: Session[]
    onClientKicked: () => void
}

export interface IClientsDialog {
    show(): void
}

export const ClientsDialog = forwardRef<IClientsDialog, Props>((props: Props, ref) => {
    const refDialog = useRef<HTMLDialogElement>(null);

    useImperativeHandle(ref, () => {
        return {
            show: () => {
                refDialog.current?.showModal();
            }
        };
    });

    const handleKickClient = async (streamId: string, clientId: string) => {
        await deleteSession(streamId, clientId);
        props.onClientKicked();
    };

    return (
        <Modal ref={refDialog} className="min-w-md max-w-[unset] w-[unset]">
            <Modal.Header className="mb-2">
                <h3 className="font-bold">Clients of {props.id}</h3>
            </Modal.Header>
            <Modal.Body>
                <Table>
                    <Table.Head>
                        <span>ID</span>
                        <span>State</span>
                        <span>Out</span>
                        <span>Creation Time</span>
                        <span>Leave Time</span>
                        <span>Operation</span>
                    </Table.Head>
                    <Table.Body>
                        {props.sessions.length > 0 ? props.sessions.map(c =>
                            <Table.Row>
                                <span>{c.id + (c.reforward ? '(reforward)' : '')}</span>
                                <span>{c.state}</span>
                                <span>{formatBitrate(c.stats?.bitrate ?? 0)}</span>
                                <span>{formatTime(c.createdAt)}</span>
                                <span>{c.leaveAt ? formatTime(c.leaveAt) : '-'}</span>
                                <Button size="sm" color="error" onClick={() => handleKickClient(props.id, c.id)} disabled={c.state === 'closed'}>Kick</Button>
                            </Table.Row>
                        ): <tr><td colspan={6} className="text-center">N/A</td></tr>}
                    </Table.Body>
                </Table>
            </Modal.Body>
            <Modal.Actions>
                <form method="dialog">
                    <Button>Close</Button>
                </form>
            </Modal.Actions>
        </Modal>
    );
});

// web/shared/components/dialog-clients.vue
<script lang="ts">
export interface IClientsDialog {
    show(): void;
}
</script>

<script setup lang="ts">
import { useTemplateRef } from "vue";

import { type Session, deleteSession } from "../api";
import { formatBitrate, formatTime } from "../utils";

interface Props {
    id: string;
    sessions: Session[];
}

const props = defineProps<Props>();

const emit = defineEmits<{
    "client-kicked": [];
}>();

const dialogEl = useTemplateRef<HTMLDialogElement>("dialogEl");

const show = () => {
    dialogEl.value?.showModal();
};

defineExpose({ show });

const handleKickClient = async (streamId: string, clientId: string) => {
    await deleteSession(streamId, clientId);
    emit("client-kicked");
};
</script>

<template>
    <dialog ref="dialogEl" aria-label="Modal" aria-hidden="true" class="modal">
        <div class="modal-box min-w-md max-w-[unset] w-[unset]">
            <div class="w-full text-xl mb-2">
                <h3 class="font-bold">Clients of {{ id }}</h3>
            </div>
            <div>
                <table class="table">
                    <thead>
                        <tr>
                            <th><span>ID</span></th>
                            <td><span>State</span></td>
                            <td><span>Out</span></td>
                            <td><span>Creation Time</span></td>
                            <td><span>Leave Time</span></td>
                            <td><span>Operation</span></td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="c in sessions" :key="c.id">
                            <th><span>{{ c.id + (c.reforward ? "(reforward)" : "") }}</span></th>
                            <td><span>{{ c.state }}</span></td>
                            <td><span>{{ formatBitrate(c.stats?.bitrate ?? 0) }}</span></td>
                            <td><span>{{ formatTime(c.createdAt) }}</span></td>
                            <td><span>{{ c.leaveAt ? formatTime(c.leaveAt) : "-" }}</span></td>
                            <td>
                                <button
                                    class="btn btn-sm btn-error"
                                    :class="{ 'btn-disabled': c.state === 'closed' }"
                                    :disabled="c.state === 'closed'"
                                    @click="handleKickClient(id, c.id)"
                                >Kick</button>
                            </td>
                        </tr>
                        <tr v-if="sessions.length === 0">
                            <td colspan="6" class="text-center">N/A</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-action">
                <form method="dialog">
                    <button class="btn">Close</button>
                </form>
            </div>
        </div>
    </dialog>
</template>
