// web/shared/components/dialog-new-stream.vue
<script lang="ts">
export interface INewStreamDialog {
    show(initialId: string): void;
}
</script>

<script setup lang="ts">
import { ref, useTemplateRef } from "vue";

import { createStream } from "../api";

const emit = defineEmits<{
    "new-stream-id": [id: string];
    "stream-created": [];
}>();

const streamId = ref("");
const dialogEl = useTemplateRef<HTMLDialogElement>("dialogEl");

const show = (initialId: string) => {
    streamId.value = initialId;
    dialogEl.value?.showModal();
};

defineExpose({ show });

function getCurrentNode(): string | null {
    const urlParams = new URLSearchParams(window.location.search);
    return urlParams.get("nodes");
}

async function handleCreateStream(id: string) {
    const currentNode = getCurrentNode();
    try {
        await createStream(id, currentNode);
        return true;
    } catch (error: unknown) {
        if (
            error instanceof Object &&
            "response" in error &&
            typeof (error as { response: { status: number } }).response.status === "number" &&
            (error as { response: { status: number } }).response.status === 409
        ) {
            window.alert("Resource already exists, please use a different streamId");
            return false;
        }
        window.alert("Failed to create stream, please try again later");
        return false;
    }
}

const closeDialog = () => {
    const activeElement = document.activeElement;
    if (activeElement instanceof HTMLElement && dialogEl.value?.contains(activeElement)) {
        activeElement.blur();
    }
    dialogEl.value?.close();
};

const onConfirmNewStreamId = async () => {
    if (!streamId.value.trim()) {
        window.alert("Please enter a valid Stream ID");
        return;
    }

    const success = await handleCreateStream(streamId.value);
    if (success) {
        closeDialog();
        emit("new-stream-id", streamId.value);
        emit("stream-created");
    }
};
</script>

<template>
    <dialog ref="dialogEl" aria-label="Modal" aria-hidden="false" class="modal">
        <div class="modal-box max-w-md">
            <div class="w-full text-xl mb-2">
                <h3 class="font-bold">New Stream</h3>
            </div>
            <div>
                <div class="form-control">
                    <label class="label px-0">Stream ID:</label>
                    <input v-model="streamId" class="input input-bordered" />
                </div>
            </div>
            <div class="modal-action">
                <form method="dialog" class="flex gap-2">
                    <button type="button" class="btn" @click="onConfirmNewStreamId">Confirm</button>
                    <button type="button" class="btn" @click="closeDialog">Cancel</button>
                </form>
            </div>
        </div>
    </dialog>
</template>

// web/shared/components/dialog-new-stream.tsx
import { useState, useRef, useImperativeHandle } from 'preact/hooks';
import { TargetedEvent, forwardRef } from 'preact/compat';
import { Button, Input, Modal } from 'react-daisyui';

import { createStream } from '../api';

interface Props {
    onNewStreamId(id: string): void;
    onStreamCreated(): void;
}

export interface INewStreamDialog {
    show(initialId: string): void;
}

export const NewStreamDialog = forwardRef<INewStreamDialog, Props>((props, ref) => {
    const [streamId, setStreamId] = useState('');
    const refDialog = useRef<HTMLDialogElement>(null);

    const closeDialog = () => {
        if (document.activeElement instanceof HTMLElement) {
            document.activeElement.blur();
        }
        refDialog.current?.close();
    };

    useImperativeHandle(ref, () => {
        return {
            show: (initialId: string) => {
                setStreamId(initialId);
                refDialog.current?.showModal();
            },
        };
    });

    const onStreamIdInput = (e: TargetedEvent<HTMLInputElement>) => {
        setStreamId(e.currentTarget.value);
    };

    function getCurrentNode(): string | null {
        const urlParams = new URLSearchParams(window.location.search);
        return urlParams.get('nodes');
    }

    async function handleCreateStream(streamId: string) {
        const currentNode = getCurrentNode();
        try {
            await createStream(streamId, currentNode);
            return true;
        } catch (error: unknown) {
            if (
                error instanceof Object &&
                'response' in error &&
                typeof (error as { response: { status: number } }).response.status === 'number' &&
                (error as { response: { status: number } }).response.status === 409
            ) {
                window.alert('Resource already exists, please use a different streamId');
                return false;
            }
            window.alert('Failed to create stream, please try again later');
            return false;
        }
    }

    const onConfirmNewStreamId = async (_e: Event) => {
        if (!streamId.trim()) {
            window.alert('Please enter a valid Stream ID');
            return;
        }

        props.onNewStreamId(streamId);
        const success = await handleCreateStream(streamId);
        if (success) {
            props.onStreamCreated();
            closeDialog();
        }
    };

    return (
        <Modal ref={refDialog} className="max-w-md">
            <Modal.Header className="mb-2">
                <h3 className="font-bold">New Stream</h3>
            </Modal.Header>
            <Modal.Body>
                <div className="form-control">
                    <label className="label px-0">Stream ID:</label>
                    <Input borderOffset value={streamId} onChange={onStreamIdInput} />
                </div>
            </Modal.Body>
            <Modal.Actions>
                <div className="flex gap-2">
                    <Button type="button" onClick={onConfirmNewStreamId}>Confirm</Button>
                    <Button type="button" onClick={closeDialog}>Cancel</Button>
                </div>
            </Modal.Actions>
        </Modal>
    );
});
