// web/shared/components/dialog-web-stream.tsx
import { useRef, useImperativeHandle, useState, useContext, useEffect } from 'preact/hooks';
import { TargetedEvent, forwardRef } from 'preact/compat';
import { Button, Collapse, Modal } from 'react-daisyui';
import { WHIPClient } from '@binbat/whip-whep/whip';

import { TokenContext } from '../context';
import { formatVideoTrackResolution } from '../utils';
import { useLogger } from '../hooks/use-logger';
import {
    DefaultQRCodeFrameRate,
    type QRCodeFrameRate,
    QRCodeFrameRates,
    QRCodeStream
} from '../qrcode-stream';
import convertSessionDescription from '../sdp-codec';

interface Props {
    getWhipUrl?: (streamId: string) => string;
    onStop(): void
}

export interface IWebStreamDialog {
    show(streamId: string): void
}

export const WebStreamDialog = forwardRef<IWebStreamDialog, Props>((props, ref) => {
    const [streamId, setStreamId] = useState('');
    const tokenContext = useContext(TokenContext);
    const refMediaStream = useRef<MediaStream | null>(null);
    const refWhipClient = useRef<WHIPClient | null>(null);
    const [connState, setConnState] = useState('');
    const [videoResolution, setVideoResolution] = useState('');
    const logger = useLogger();
    const refDialog = useRef<HTMLDialogElement>(null);
    const refVideo = useRef<HTMLVideoElement>(null);
    const refCanvas = useRef<HTMLCanvasElement>(null);
    const refQrCodeStream = useRef<QRCodeStream>(null);
    const [qrPreviewing, setQrPreviewing] = useState(false);
    const [qrSourceHidden, setQrSourceHidden] = useState(false);
    const refQrSourceHiddenLogged = useRef(false);
    const [qrFrameRate, setQrFrameRate] = useState<QRCodeFrameRate>(
        DefaultQRCodeFrameRate
    );

    useImperativeHandle(ref, () => {
        return {
            show: (streamId: string) => {
                setStreamId(streamId);
                refDialog.current?.showModal();
            }
        };
    });

    const handleCloseDialog = () => {
        refDialog.current?.close();
    };

    const updateConnState = (state: string) => {
        setConnState(state);
        logger.log(state);
    };

    useEffect(() => {
        const handleVisibilityChange = () => {
            if (
                document.visibilityState !== 'hidden' ||
                !refQrCodeStream.current ||
                !refWhipClient.current
            ) {
                return;
            }
            setQrSourceHidden(true);
            if (!refQrSourceHiddenLogged.current) {
                logger.log('QR source page is hidden; browser timer throttling may reduce QR fps.');
                refQrSourceHiddenLogged.current = true;
            }
        };
        document.addEventListener('visibilitychange', handleVisibilityChange);
        return () => {
            document.removeEventListener('visibilitychange', handleVisibilityChange);
        };
    }, []);

    const handleStreamStart = async (stream: MediaStream) => {
        logger.clear();
        setConnState('');
        refMediaStream.current = stream;
        if (refVideo.current) {
            refVideo.current.srcObject = stream;
        }
        updateConnState('Started');
        const pc = new RTCPeerConnection();
        pc.addEventListener('iceconnectionstatechange', () => {
            updateConnState(pc.iceConnectionState);
        });
        stream.getVideoTracks().forEach(vt => {
            pc.addTransceiver(vt, { direction: 'sendonly' });
            setVideoResolution(formatVideoTrackResolution(vt));
        });
        stream.getAudioTracks().forEach(at => {
            pc.addTransceiver(at, { direction: 'sendonly' });
        });
        const whip = new WHIPClient();
        refWhipClient.current = whip;
        whip.onOffer = sdp => {
            logger.log('http offer sent');
            try {
                return convertSessionDescription(sdp, '', 'h264');
            } catch (error) {
                const message = error instanceof Error ? error.message : 'H264 is not available';
                logger.log(message);
                throw error;
            }
        };
        whip.onAnswer = sdp => {
            logger.log('http answer received');
            return sdp;
        };
        try {
            const url = props.getWhipUrl?.(streamId) ?? `${location.origin}/whip/${streamId}`;
            await whip.publish(pc, url, tokenContext.token);
        } catch (e: any) {  // eslint-disable-line @typescript-eslint/no-explicit-any
            setConnState('Error');
            if (e instanceof Error) {
                logger.log(e.message);
            }
            const r = e.response as Response | undefined;
            if (r) {
                logger.log(await r.text());
            }
        }
    };

    const handleDisplayMediaStart = async () => {
        const stream = await navigator.mediaDevices.getDisplayMedia({
            audio: true,
            video: true
        });
        handleStreamStart(stream);
    };

    const handleEncodeLatencyPreview = () => {
        setQrSourceHidden(false);
        refQrSourceHiddenLogged.current = false;
        if (!refQrCodeStream.current) {
            refQrCodeStream.current = new QRCodeStream(
                refCanvas.current!,
                qrFrameRate
            );
        }
        const stream = refQrCodeStream.current.capture();
        refMediaStream.current = stream;
        if (refVideo.current) {
            refVideo.current.srcObject = stream;
        }
        setQrPreviewing(true);
    };

    const updateQrFrameRate = (frameRate: QRCodeFrameRate) => {
        setQrFrameRate(frameRate);
        if (!qrPreviewing || refWhipClient.current) {
            return;
        }

        if (refQrCodeStream.current) {
            refQrCodeStream.current.stop();
            refQrCodeStream.current = null;
        }
        refQrCodeStream.current = new QRCodeStream(
            refCanvas.current!,
            frameRate
        );
        const stream = refQrCodeStream.current.capture();
        refMediaStream.current = stream;
        if (refVideo.current) {
            refVideo.current.srcObject = stream;
        }
        logger.log(`QR source updated to ${frameRate} fps.`);
    };

    const handleEncodeLatencyPublish = () => {
        if (refMediaStream.current) {
            handleStreamStart(refMediaStream.current);
            logger.log('For QR latency testing, keep this source page visible and use Preview -> Decode Latency on this page.');
            setQrPreviewing(false);
        }
    };

    const handleStreamStop = async () => {
        setQrPreviewing(false);
        setQrSourceHidden(false);
        refQrSourceHiddenLogged.current = false;
        if (refQrCodeStream.current) {
            refQrCodeStream.current.stop();
            refQrCodeStream.current = null;
        }
        if (refMediaStream.current) {
            refMediaStream.current.getTracks().forEach(t => t.stop());
            refMediaStream.current = null;
        }
        if (refVideo.current) {
            refVideo.current.srcObject = null;
        }
        if (refWhipClient.current) {
            await refWhipClient.current.stop();
            refWhipClient.current = null;
        }
        props.onStop();
        handleCloseDialog();
    };

    const handleVideoResize = (_: TargetedEvent<HTMLVideoElement>) => {
        const videoTrack = refMediaStream.current?.getVideoTracks()[0];
        if (videoTrack) {
            setVideoResolution(formatVideoTrackResolution(videoTrack));
        }
    };

    return (
        <Modal ref={refDialog} className="min-w-md max-w-[unset] w-[unset]" ariaHidden={false}>
            <Modal.Header className="mb-6">
                <h3 className="font-bold">Web Stream {streamId} {videoResolution}</h3>
            </Modal.Header>
            <Modal.Body>
                <video
                    ref={refVideo}
                    className="block mx-auto min-w-[28rem] max-w-[90vw] max-h-[70vh]"
                    onResize={handleVideoResize}
                    controls autoplay
                />
                <Collapse.Details icon="arrow" className="text-sm">
                    <Collapse.Details.Title className="px-0">
                        <b>Connection Status: </b>
                        <code>{connState}</code>
                    </Collapse.Details.Title>
                    <Collapse.Content className="px-0">
                        <pre class="overflow-auto max-h-[10lh]">{logger.logs.join('\n')}</pre>
                    </Collapse.Content>
                </Collapse.Details>
                {qrSourceHidden ? (
                    <div className="alert alert-warning mt-2">
                        <span>QR source page was hidden; browser timer throttling may reduce QR fps.</span>
                    </div>
                ) : null}
            </Modal.Body>
            <Modal.Actions className="mt-0">
                <label className="mr-auto">
                    QR Frame Rate:
                    <select
                        disabled={!!refWhipClient.current}
                        value={qrFrameRate}
                        onChange={(e) => {
                            updateQrFrameRate(
                                Number.parseInt(
                                    e.currentTarget.value,
                                    10
                                ) as QRCodeFrameRate
                            );
                        }}
                    >
                        {QRCodeFrameRates.map(frameRate => (
                            <option value={frameRate}>{frameRate} fps</option>
                        ))}
                    </select>
                </label>
                {refWhipClient.current ? (
                    <Button color="error" onClick={handleStreamStop}>Stop</Button>
                ) : qrPreviewing ? (
                    <>
                        <Button color="success" onClick={handleEncodeLatencyPublish}>Publish</Button>
                        <Button color="error" onClick={handleStreamStop}>Stop</Button>
                    </>
                ) : (
                    <>
                        <Button color="info" onClick={handleEncodeLatencyPreview}>Encode Latency</Button>
                        <Button onClick={handleDisplayMediaStart}>Start</Button>
                    </>
                )}
                <Button onClick={handleCloseDialog}>Hide</Button>
            </Modal.Actions>
            <canvas ref={refCanvas} class="hidden" width={1280} height={720}></canvas>
        </Modal>
    );
});

// web/shared/components/dialog-web-stream.vue
<script lang="ts">
export interface IWebStreamDialog {
    show(streamId: string): void;
}
</script>

<script setup lang="ts">
import { onMounted, onUnmounted, ref, shallowRef, useTemplateRef } from "vue";
import { WHIPClient } from "@binbat/whip-whep/whip";

import { useToken } from "../context";
import { formatVideoTrackResolution } from "../utils";
import { useLogger } from "../hooks/use-logger";
import {
    DefaultQRCodeFrameRate,
    type QRCodeFrameRate,
    QRCodeFrameRates,
    QRCodeStream
} from "../qrcode-stream";
import convertSessionDescription from "../sdp-codec";

interface Props {
    getWhipUrl?: (streamId: string) => string;
}

const props = defineProps<Props>();

const emit = defineEmits<{
    stop: [];
}>();

const streamId = ref("");
const token = useToken();
let mediaStream: MediaStream | null = null;
const whipClient = shallowRef<WHIPClient | null>(null);
const connState = ref("");
const videoResolution = ref("");
const { logs, log, clear } = useLogger();
const dialogEl = useTemplateRef<HTMLDialogElement>("dialogEl");
const videoEl = useTemplateRef<HTMLVideoElement>("videoEl");
const canvasEl = useTemplateRef<HTMLCanvasElement>("canvasEl");
let qrCodeStream: QRCodeStream | null = null;
const qrPreviewing = ref(false);
const qrSourceHidden = ref(false);
let qrSourceHiddenLogged = false;
const qrFrameRate = ref<QRCodeFrameRate>(DefaultQRCodeFrameRate);

const show = (id: string) => {
    streamId.value = id;
    dialogEl.value?.showModal();
};

defineExpose({ show });

const handleCloseDialog = () => {
    dialogEl.value?.close();
};

const updateConnState = (state: string) => {
    connState.value = state;
    log(state);
};

const handleVisibilityChange = () => {
    if (
        document.visibilityState !== "hidden" ||
        !qrCodeStream ||
        !whipClient.value
    ) {
        return;
    }
    qrSourceHidden.value = true;
    if (!qrSourceHiddenLogged) {
        log("QR source page is hidden; browser timer throttling may reduce QR fps.");
        qrSourceHiddenLogged = true;
    }
};

onMounted(() => {
    document.addEventListener("visibilitychange", handleVisibilityChange);
});

onUnmounted(() => {
    document.removeEventListener("visibilitychange", handleVisibilityChange);
});

const handleStreamStart = async (stream: MediaStream) => {
    clear();
    connState.value = "";
    mediaStream = stream;
    if (videoEl.value) {
        videoEl.value.srcObject = stream;
    }
    updateConnState("Started");
    const pc = new RTCPeerConnection();
    pc.addEventListener("iceconnectionstatechange", () => {
        updateConnState(pc.iceConnectionState);
    });
    stream.getVideoTracks().forEach(vt => {
        pc.addTransceiver(vt, { direction: "sendonly" });
        videoResolution.value = formatVideoTrackResolution(vt);
    });
    stream.getAudioTracks().forEach(at => {
        pc.addTransceiver(at, { direction: "sendonly" });
    });
    const whip = new WHIPClient();
    whipClient.value = whip;
    whip.onOffer = sdp => {
        log("http offer sent");
        try {
            return convertSessionDescription(sdp, "", "h264");
        } catch (error) {
            const message = error instanceof Error ? error.message : "H264 is not available";
            log(message);
            throw error;
        }
    };
    whip.onAnswer = sdp => {
        log("http answer received");
        return sdp;
    };
    try {
        const url = props.getWhipUrl?.(streamId.value) ?? `${location.origin}/whip/${streamId.value}`;
        await whip.publish(pc, url, token.value);
    } catch (e: any) {  // eslint-disable-line @typescript-eslint/no-explicit-any
        connState.value = "Error";
        if (e instanceof Error) {
            log(e.message);
        }
        const r = e.response as Response | undefined;
        if (r) {
            log(await r.text());
        }
    }
};

const handleDisplayMediaStart = async () => {
    const stream = await navigator.mediaDevices.getDisplayMedia({
        audio: true,
        video: true
    });
    void handleStreamStart(stream);
};

const handleEncodeLatencyPreview = () => {
    qrSourceHidden.value = false;
    qrSourceHiddenLogged = false;
    if (!qrCodeStream) {
        qrCodeStream = new QRCodeStream(
            canvasEl.value!,
            qrFrameRate.value
        );
    }
    const stream = qrCodeStream.capture();
    mediaStream = stream;
    if (videoEl.value) {
        videoEl.value.srcObject = stream;
    }
    qrPreviewing.value = true;
};

const updateQrFrameRate = (frameRate: QRCodeFrameRate) => {
    qrFrameRate.value = frameRate;
    if (!qrPreviewing.value || whipClient.value) {
        return;
    }

    if (qrCodeStream) {
        qrCodeStream.stop();
        qrCodeStream = null;
    }
    qrCodeStream = new QRCodeStream(
        canvasEl.value!,
        frameRate
    );
    const stream = qrCodeStream.capture();
    mediaStream = stream;
    if (videoEl.value) {
        videoEl.value.srcObject = stream;
    }
    log(`QR source updated to ${frameRate} fps.`);
};

const handleQrFrameRateChange = (e: Event) => {
    updateQrFrameRate(
        Number.parseInt(
            (e.currentTarget as HTMLSelectElement).value,
            10
        ) as QRCodeFrameRate
    );
};

const handleEncodeLatencyPublish = () => {
    if (mediaStream) {
        void handleStreamStart(mediaStream);
        log("For QR latency testing, keep this source page visible and use Preview -> Decode Latency on this page.");
        qrPreviewing.value = false;
    }
};

const handleStreamStop = async () => {
    qrPreviewing.value = false;
    qrSourceHidden.value = false;
    qrSourceHiddenLogged = false;
    if (qrCodeStream) {
        qrCodeStream.stop();
        qrCodeStream = null;
    }
    if (mediaStream) {
        mediaStream.getTracks().forEach(t => t.stop());
        mediaStream = null;
    }
    if (videoEl.value) {
        videoEl.value.srcObject = null;
    }
    if (whipClient.value) {
        await whipClient.value.stop();
        whipClient.value = null;
    }
    emit("stop");
    handleCloseDialog();
};

const handleVideoResize = () => {
    const videoTrack = mediaStream?.getVideoTracks()[0];
    if (videoTrack) {
        videoResolution.value = formatVideoTrackResolution(videoTrack);
    }
};
</script>

<template>
    <dialog ref="dialogEl" aria-label="Modal" aria-hidden="false" class="modal">
        <div class="modal-box sm:min-w-md sm:max-w-[unset] sm:w-[unset]">
            <div class="w-full text-xl mb-6">
                <h3 class="font-bold">Web Stream {{ streamId }} {{ videoResolution }}</h3>
            </div>
            <div>
                <video
                    ref="videoEl"
                    class="block mx-auto sm:min-w-[28rem] max-w-[90vw] max-h-[70vh]"
                    controls
                    autoplay
                    @resize="handleVideoResize"
                ></video>
                <details class="collapse collapse-arrow text-sm">
                    <summary class="collapse-title px-0">
                        <b>Connection Status: </b>
                        <code>{{ connState }}</code>
                    </summary>
                    <div class="collapse-content px-0">
                        <pre class="overflow-auto max-h-[10lh]">{{ logs.join("\n") }}</pre>
                    </div>
                </details>
                <div v-if="qrSourceHidden" class="alert alert-warning mt-2">
                    <span>QR source page was hidden; browser timer throttling may reduce QR fps.</span>
                </div>
            </div>
            <div class="modal-action mt-0">
                <label class="mr-auto">
                    QR Frame Rate:
                    <select
                        :disabled="!!whipClient"
                        :value="qrFrameRate"
                        @change="handleQrFrameRateChange"
                    >
                        <option v-for="frameRate in QRCodeFrameRates" :key="frameRate" :value="frameRate">
                            {{ frameRate }} fps
                        </option>
                    </select>
                </label>
                <button v-if="whipClient" class="btn btn-error" @click="handleStreamStop">Stop</button>
                <template v-else-if="qrPreviewing">
                    <button class="btn btn-success" @click="handleEncodeLatencyPublish">Publish</button>
                    <button class="btn btn-error" @click="handleStreamStop">Stop</button>
                </template>
                <template v-else>
                    <button class="btn btn-info" @click="handleEncodeLatencyPreview">Encode Latency</button>
                    <button class="btn" @click="handleDisplayMediaStart">Start</button>
                </template>
                <button class="btn" @click="handleCloseDialog">Hide</button>
            </div>
            <canvas ref="canvasEl" class="hidden" width="1280" height="720"></canvas>
        </div>
    </dialog>
</template>
