// web/shared/components/page-layout.tsx
import { type PropsWithChildren } from 'preact/compat';
import { PageHeader } from './page-header';

import { type ITokenContext, TokenContext } from '../context';

export interface PageLayoutProps extends PropsWithChildren<ITokenContext> {
    currentView?: string;
    onNavigate?: (view: string) => void;
    enabledTools?: {
        debugger?: boolean;
        player?: boolean;
        dash?: boolean;
        recordings?: boolean;
    };
}

export function PageLayout({ token, currentView, onNavigate, enabledTools, children }: PageLayoutProps) {
    return (
        <TokenContext.Provider value={{ token }}>
            <PageHeader currentView={currentView} onNavigate={onNavigate} enabledTools={enabledTools} />
            <div className="max-w-screen-xl mx-auto">
                {children}
            </div>
        </TokenContext.Provider>
    );
}

// web/shared/components/page-layout.vue
<script lang="ts">
export interface PageLayoutProps {
    token: string;
    currentView?: string;
    /** Function prop, forwarded to PageHeader (see its docs). */
    onNavigate?: (view: string) => void;
    enabledTools?: {
        debugger?: boolean;
        player?: boolean;
        dash?: boolean;
        recordings?: boolean;
    };
}
</script>

<script setup lang="ts">
import { toRef } from "vue";

import PageHeader from "./page-header.vue";
import { provideToken } from "../context";

const props = defineProps<PageLayoutProps>();

provideToken(toRef(props, "token"));
</script>

<template>
    <PageHeader
        :current-view="currentView"
        :on-navigate="onNavigate"
        :enabled-tools="enabledTools"
    />
    <div class="max-w-screen-xl mx-auto">
        <slot />
    </div>
</template>
