// web/shared/components/virtual-scroll.vue
<script setup lang="ts" generic="T">
import { computed, ref } from "vue";

interface VirtualScrollProps<T> {
    items: T[];
    itemHeight: number;
    containerHeight: number;
    overscan?: number;
}

const props = withDefaults(defineProps<VirtualScrollProps<T>>(), {
    overscan: 5,
});

const scrollTop = ref(0);

const view = computed(() => {
    const startIndex = Math.floor(scrollTop.value / props.itemHeight);
    const endIndex = Math.min(
        startIndex + Math.ceil(props.containerHeight / props.itemHeight) + props.overscan,
        props.items.length
    );

    const visibleStartIndex = Math.max(0, startIndex - props.overscan);
    const visibleItems = props.items.slice(visibleStartIndex, endIndex);

    return {
        visibleItems: visibleItems.map((item, index) => ({
            item,
            index: visibleStartIndex + index
        })),
        totalHeight: props.items.length * props.itemHeight,
        offsetY: visibleStartIndex * props.itemHeight
    };
});

const handleScroll = (event: Event) => {
    scrollTop.value = (event.target as HTMLDivElement).scrollTop;
};
</script>

<template>
    <div :style="{ height: `${containerHeight}px`, overflow: 'auto' }" @scroll="handleScroll">
        <div :style="{ height: `${view.totalHeight}px`, position: 'relative' }">
            <div :style="{ transform: `translateY(${view.offsetY}px)` }">
                <div v-for="{ item, index } in view.visibleItems" :key="index" :style="{ height: `${itemHeight}px` }">
                    <slot name="item" :item="item" :index="index" />
                </div>
            </div>
        </div>
    </div>
</template>

// web/shared/components/virtual-scroll.tsx
import { useMemo, useRef, useState } from 'preact/hooks';

interface VirtualScrollProps<T> {
    items: T[];
    itemHeight: number;
    containerHeight: number;
    renderItem: (item: T, index: number) => preact.ComponentChild;
    overscan?: number;
}

export function VirtualScroll<T>({ 
    items, 
    itemHeight, 
    containerHeight,
    renderItem,
    overscan = 5 
}: VirtualScrollProps<T>) {
    const [scrollTop, setScrollTop] = useState(0);
    const scrollElementRef = useRef<HTMLDivElement>(null);

    const { visibleItems, totalHeight, offsetY } = useMemo(() => {
        const startIndex = Math.floor(scrollTop / itemHeight);
        const endIndex = Math.min(
            startIndex + Math.ceil(containerHeight / itemHeight) + overscan,
            items.length
        );

        const visibleStartIndex = Math.max(0, startIndex - overscan);
        const visibleItems = items.slice(visibleStartIndex, endIndex);
        
        return {
            visibleItems: visibleItems.map((item, index) => ({
                item,
                index: visibleStartIndex + index
            })),
            totalHeight: items.length * itemHeight,
            offsetY: visibleStartIndex * itemHeight
        };
    }, [items, itemHeight, scrollTop, containerHeight, overscan]);

    const handleScroll = (event: Event) => {
        const target = event.target as HTMLDivElement;
        setScrollTop(target.scrollTop);
    };

    return (
        <div
            ref={scrollElementRef}
            onScroll={handleScroll}
            style={{ height: containerHeight, overflow: 'auto' }}
        >
            <div style={{ height: totalHeight, position: 'relative' }}>
                <div style={{ transform: `translateY(${offsetY}px)` }}>
                    {visibleItems.map(({ item, index }) => (
                        <div key={index} style={{ height: itemHeight }}>
                            {renderItem(item, index)}
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
}
