// web/debugger/components/device.vue
<script setup lang="ts">
import { ref, watch } from "vue";

const NoneDevice = { value: "", text: "none" };

function deviceInfoToOption(info: MediaDeviceInfo) {
    const value = info.deviceId;
    let text = info.label;
    if (text.length <= 0) {
        text = `${info.kind} (${info.deviceId})`;
    }
    return { value, text };
}

function uniqByValue<T extends { value: unknown }>(items: T[]) {
    const map = new Map<unknown, T>();
    for (const item of items) {
        if (!map.has(item.value)) {
            map.set(item.value, item);
        }
    }
    return Array.from(map.values());
}

const props = defineProps<{
    disabled: boolean;
    refreshToken: number;
}>();

const emit = defineEmits<{
    selectAudio: [deviceId: string];
    selectVideo: [deviceId: string];
}>();

const audioDevices = ref([NoneDevice]);
const videoDevices = ref([NoneDevice]);

const refreshDevice = async () => {
    try {
        // to obtain non-empty device label, there needs to be an active media stream or persistent permission
        // https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo/label#value
        const mediaStream = await navigator.mediaDevices.getUserMedia({
            audio: true,
            video: true,
        });
        const devices = (
            await navigator.mediaDevices.enumerateDevices()
        ).filter((i) => !!i.deviceId);
        mediaStream.getTracks().map((track) => track.stop());
        const audio = devices
            .filter((i) => i.kind === "audioinput")
            .map(deviceInfoToOption);
        if (audio.length > 0) {
            audioDevices.value = uniqByValue(audio);
        }
        const video = devices
            .filter((i) => i.kind === "videoinput")
            .map(deviceInfoToOption);
        if (video.length > 0) {
            videoDevices.value = uniqByValue(video);
        }
    } catch (e) {
        console.error("refreshDevice failed:", e);
    }
};

watch(
    () => props.refreshToken,
    () => {
        void refreshDevice();
    },
);
watch(audioDevices, (items) => {
    if (items.length > 0) {
        emit("selectAudio", items[0].value);
    }
});
watch(videoDevices, (items) => {
    if (items.length > 0) {
        emit("selectVideo", items[0].value);
    }
});
</script>

<template>
    <div style="margin: 0.2rem">
        Audio Device:
        <select
            :disabled="disabled"
            @change="emit('selectAudio', ($event.target as HTMLSelectElement).value)"
        >
            <option v-for="d in audioDevices" :key="d.value" :value="d.value">
                {{ d.text }}
            </option>
        </select>
    </div>
    <div style="margin: 0.2rem">
        Video Device:
        <select
            :disabled="disabled"
            @change="emit('selectVideo', ($event.target as HTMLSelectElement).value)"
        >
            <option v-for="d in videoDevices" :key="d.value" :value="d.value">
                {{ d.text }}
            </option>
        </select>
    </div>
</template>

// web/debugger/components/device.tsx
import { createEffect, createSignal, on } from "solid-js";

const NoneDevice = { value: "", text: "none" };

function deviceInfoToOption(info: MediaDeviceInfo) {
    const value = info.deviceId;
    let text = info.label;
    if (text.length <= 0) {
        text = `${info.kind} (${info.deviceId})`;
    }
    return { value, text };
}

function uniqByValue<T extends { value: unknown }>(items: T[]) {
    const map = new Map<unknown, T>();
    for (const item of items) {
        if (!map.has(item.value)) {
            map.set(item.value, item);
        }
    }
    return Array.from(map.values());
}

export default function Device(props: {
    disabled: boolean;
    refreshToken: number;
    onSelectAudio: (deviceId: string) => void;
    onSelectVideo: (deviceId: string) => void;
}) {
    const [audioDevices, setAudioDevices] = createSignal([NoneDevice]);
    const [videoDevices, setVideoDevices] = createSignal([NoneDevice]);

    const refreshDevice = async () => {
        try {
            // to obtain non-empty device label, there needs to be an active media stream or persistent permission
            // https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo/label#value
            const mediaStream = await navigator.mediaDevices.getUserMedia({
                audio: true,
                video: true,
            });
            const devices = (
                await navigator.mediaDevices.enumerateDevices()
            ).filter((i) => !!i.deviceId);
            mediaStream.getTracks().map((track) => track.stop());
            const audio = devices
                .filter((i) => i.kind === "audioinput")
                .map(deviceInfoToOption);
            if (audio.length > 0) {
                setAudioDevices(uniqByValue(audio));
            }
            const video = devices
                .filter((i) => i.kind === "videoinput")
                .map(deviceInfoToOption);
            if (video.length > 0) {
                setVideoDevices(uniqByValue(video));
            }
        } catch (e) {
            console.error("refreshDevice failed:", e);
        }
    };
    createEffect(
        on(
            () => props.refreshToken,
            () => {
                void refreshDevice();
            },
            {
                defer: true,
            },
        ),
    );
    createEffect(
        on(
            audioDevices,
            (i) => i.length > 0 && props.onSelectAudio(i[0].value),
            {
                defer: true,
            },
        ),
    );
    createEffect(
        on(
            videoDevices,
            (i) => i.length > 0 && props.onSelectVideo(i[0].value),
            {
                defer: true,
            },
        ),
    );

    return (
        <>
            <div style="margin: 0.2rem">
                Audio Device:
                <select
                    disabled={props.disabled}
                    onChange={(e) => {
                        props.onSelectAudio(e.target.value);
                    }}
                >
                    {audioDevices().map((d) => (
                        <option value={d.value}>{d.text}</option>
                    ))}
                </select>
            </div>
            <div style="margin: 0.2rem">
                Video Device:
                <select
                    disabled={props.disabled}
                    onChange={(e) => {
                        props.onSelectVideo(e.target.value);
                    }}
                >
                    {videoDevices().map((d) => (
                        <option value={d.value}>{d.text}</option>
                    ))}
                </select>
            </div>
        </>
    );
}
