// web/liveion/components/login.tsx
import { useEffect, useRef, useState } from 'preact/hooks';
import { TargetedEvent } from 'preact/compat';
import { Alert, Button, Loading, Modal } from 'react-daisyui';
import { WretchError } from 'wretch/resolver';

import * as api from '@/shared/api';
import { formatHttpError } from '@/shared/utils';

export interface LoginProps {
    show: boolean;
    onSuccess?: (token: string) => void;
}

export function Login({ show, onSuccess }: LoginProps) {
    const refDialog = useRef<HTMLDialogElement>(null);
    const [token, setToken] = useState('');
    const [loading, setLoading] = useState(false);
    const [errMsg, setErrMsg] = useState<string | null>(null);

    useEffect(() => {
        if (show) {
            refDialog.current?.showModal();
        } else {
            refDialog.current?.close();
        }
    }, [show]);

    const handleDialogClose = () => {
        if (show) {
            refDialog.current?.showModal();
        }
    };

    const onTokenSubmit = async (e: TargetedEvent) => {
        setLoading(true);
        e.preventDefault();
        const tk = token.indexOf(' ') < 0 ? `Bearer ${token}` : token;
        api.setAuthToken(tk);
        try {
            await api.getStreams();
            onSuccess?.(token);
        } catch (e) {
            api.setAuthToken('');
            if (e instanceof WretchError) {
                setErrMsg(formatHttpError(e));
            } else if (e instanceof Error) {
                setErrMsg(e.message);
            } else {
                setErrMsg(String(e));
            }
        }
        setLoading(false);
    };

    return (
        <Modal ref={refDialog} onClose={handleDialogClose}>
            <Modal.Header>
                <h3 className="font-bold">Authorization Required</h3>
            </Modal.Header>
            {typeof errMsg === 'string' ? <Alert status="error" >{errMsg}</Alert> : null}
            <form onSubmit={onTokenSubmit}>
                <label class="input input-bordered flex items-center gap-2 my-4">
                    <span>Token</span>
                    <input class="grow" value={token} onInput={e => setToken(e.currentTarget?.value)} />
                </label>
                <Button color="primary" className="w-full text-base" disabled={loading}>
                    {loading ? <Loading size="sm" /> : null}
                    <span>Login</span>
                </Button>
            </form>
        </Modal>
    );
}

// web/liveion/components/login.vue
<script setup lang="ts">
import { ref, useTemplateRef, watch } from "vue";
import { WretchError } from "wretch/resolver";

import * as api from "@/shared/api";
import { formatHttpError } from "@/shared/utils";

interface Props {
    show: boolean;
}

const props = defineProps<Props>();

const emit = defineEmits<{
    success: [token: string];
}>();

const dialogEl = useTemplateRef<HTMLDialogElement>("dialogEl");
const token = ref("");
const loading = ref(false);
const errMsg = ref<string | null>(null);

watch(() => props.show, (show) => {
    const dialog = dialogEl.value;
    if (!dialog) {
        return;
    }
    if (show && !dialog.open) {
        dialog.showModal();
    } else if (!show && dialog.open) {
        dialog.close();
    }
});

const handleDialogClose = () => {
    if (props.show) {
        dialogEl.value?.showModal();
    }
};

const onTokenSubmit = async () => {
    loading.value = true;
    const tk = token.value.indexOf(" ") < 0 ? `Bearer ${token.value}` : token.value;
    api.setAuthToken(tk);
    try {
        await api.getStreams();
        emit("success", token.value);
    } catch (e) {
        api.setAuthToken("");
        if (e instanceof WretchError) {
            errMsg.value = formatHttpError(e);
        } else if (e instanceof Error) {
            errMsg.value = e.message;
        } else {
            errMsg.value = String(e);
        }
    }
    loading.value = false;
};
</script>

<template>
    <dialog ref="dialogEl" aria-label="Modal" aria-hidden="true" class="modal" @close="handleDialogClose">
        <div class="modal-box">
            <div class="w-full mb-8 text-xl">
                <h3 class="font-bold">Authorization Required</h3>
            </div>
            <div v-if="typeof errMsg === 'string'" role="alert" class="alert alert-error">{{ errMsg }}</div>
            <form @submit.prevent="onTokenSubmit">
                <label class="input input-bordered flex items-center gap-2 my-4">
                    <span>Token</span>
                    <input v-model="token" class="grow" />
                </label>
                <button type="submit" class="btn btn-primary w-full text-base" :disabled="loading">
                    <span v-if="loading" class="loading loading-spinner loading-sm"></span>
                    <span>Login</span>
                </button>
            </form>
        </div>
    </dialog>
</template>
