// web/player-core/player-surface.tsx
import { createEffect, createSignal, onCleanup, onMount, Show } from "solid-js";
import StatsForNerds from "./stats";
import type { StatsNerds } from "./types";
import { collectWebRtcStats } from "./webrtc-stats";

interface Props {
    stream?: MediaStream | null;
    autoplay?: boolean;
    muted?: boolean;
    controls?: boolean;
    onClick?: (event: MouseEvent) => void;
    onVideoElement?: (video: HTMLVideoElement) => void;
    getPeerConnection?: () => RTCPeerConnection | null;
}

export default function PlayerSurface(props: Props) {
    const [statsNerds, setStatsNerds] = createSignal<StatsNerds | null>(null);

    let ref: HTMLVideoElement | undefined;
    let statsInterval: ReturnType<typeof setInterval> | null = null;
    let detachStreamListeners: (() => void) | undefined;

    const play = () => {
        if (!props.autoplay || !ref || !ref.srcObject) return;
        ref.muted = !!props.muted;
        ref.play().catch(() => {
            // Autoplay can be blocked if the caller does not mute the video.
        });
    };

    createEffect(() => {
        if (ref) {
            ref.srcObject = props.stream ?? null;
            queueMicrotask(play);
        }
    });

    createEffect(() => {
        detachStreamListeners?.();
        detachStreamListeners = undefined;
        if (!ref || !props.stream) return;

        const currentRef = ref;
        currentRef.addEventListener("loadedmetadata", play);
        currentRef.addEventListener("canplay", play);
        detachStreamListeners = () => {
            currentRef.removeEventListener("loadedmetadata", play);
            currentRef.removeEventListener("canplay", play);
        };
        play();
    });

    createEffect(() => {
        if (ref) {
            props.onVideoElement?.(ref);
        }
    });

    const stopSyncStats = () => {
        if (statsInterval) {
            clearInterval(statsInterval);
            statsInterval = null;
        }
        setStatsNerds(null);
    };

    const syncStats = async () => {
        const peerConnection = props.getPeerConnection?.();
        if (!peerConnection) return;

        const stats = await collectWebRtcStats(peerConnection);
        stats.muted = ref?.muted;
        setStatsNerds(stats);
    };

    const startSyncStats = () => {
        if (statsInterval) return;
        syncStats();
        statsInterval = setInterval(syncStats, 1000);
    };

    onMount(() => {
        ref?.addEventListener("contextmenu", startSyncStats);
    });

    onCleanup(() => {
        detachStreamListeners?.();
        ref?.removeEventListener("contextmenu", startSyncStats);
        stopSyncStats();
    });

    return (
        <div id="player" class="player-wrapper">
            <video
                ref={ref}
                autoplay={props.autoplay}
                muted={props.muted}
                controls={props.controls}
                onClick={props.onClick}
                playsinline
            />
            <Show when={statsNerds()}>
                {(stats) => (
                    <div class="stats-container" id="stats">
                        <StatsForNerds
                            stats={stats()}
                            onClose={stopSyncStats}
                        />
                    </div>
                )}
            </Show>
        </div>
    );
}

// web/player-vue/player-surface.vue
<script setup lang="ts">
import { collectWebRtcStats, type StatsNerds } from "player-core";
import { onMounted, onUnmounted, ref, useTemplateRef, watchEffect } from "vue";
import StatsForNerds from "./stats-for-nerds.vue";

interface Props {
    stream?: MediaStream | null;
    autoplay?: boolean;
    muted?: boolean;
    controls?: boolean;
    getPeerConnection?: () => RTCPeerConnection | null;
}

const props = withDefaults(defineProps<Props>(), {
    stream: null,
    autoplay: false,
    muted: false,
    controls: false,
});

const emit = defineEmits<{
    click: [event: MouseEvent];
    "video-element": [video: HTMLVideoElement];
}>();

const videoEl = useTemplateRef("videoEl");
const statsNerds = ref<StatsNerds | null>(null);
let statsInterval: ReturnType<typeof setInterval> | null = null;

const tryPlay = () => {
    const video = videoEl.value;
    if (!props.autoplay || !video?.srcObject) return;
    video.muted = props.muted;
    video.play().catch(() => {
        // Autoplay can be blocked if the caller does not mute the video.
    });
};

watchEffect(
    (onCleanup) => {
        const video = videoEl.value;
        if (!video) return;
        video.srcObject = props.stream ?? null;
        queueMicrotask(tryPlay);
        if (!props.stream) return;
        video.addEventListener("loadedmetadata", tryPlay);
        video.addEventListener("canplay", tryPlay);
        onCleanup(() => {
            video.removeEventListener("loadedmetadata", tryPlay);
            video.removeEventListener("canplay", tryPlay);
        });
    },
    { flush: "post" },
);

const stopSyncStats = () => {
    if (statsInterval) {
        clearInterval(statsInterval);
        statsInterval = null;
    }
    statsNerds.value = null;
};

const syncStats = async () => {
    const peerConnection = props.getPeerConnection?.();
    if (!peerConnection) return;

    const stats = await collectWebRtcStats(peerConnection);
    stats.muted = videoEl.value?.muted;
    statsNerds.value = stats;
};

const startSyncStats = () => {
    if (statsInterval) return;
    void syncStats();
    statsInterval = setInterval(syncStats, 1000);
};

onMounted(() => {
    const video = videoEl.value;
    if (!video) return;
    emit("video-element", video);
    video.addEventListener("contextmenu", startSyncStats);
});

onUnmounted(() => {
    videoEl.value?.removeEventListener("contextmenu", startSyncStats);
    stopSyncStats();
});
</script>

<template>
    <div id="player" class="player-wrapper">
        <video
            ref="videoEl"
            :autoplay="autoplay"
            :muted="muted"
            :controls="controls"
            playsinline
            @click="emit('click', $event)"
        />
        <div v-if="statsNerds" id="stats" class="stats-container">
            <StatsForNerds :stats="statsNerds" @close="stopSyncStats" />
        </div>
    </div>
</template>
