// web/liveman/components/dialog-token.tsx
import { useState, useRef, useImperativeHandle, useEffect } from 'preact/hooks';
import { forwardRef } from 'preact/compat';
import { Button, Checkbox, Input, Modal } from 'react-daisyui';

import { createStreamToken } from '../api';

enum StreamTokenPermission {
    Sub = 'subscribe',
    Pub = 'publish',
    Admin = 'admin'
}

export interface IStreamTokenDialog {
    show(id: string): void
}

export const StreamTokenDialog = forwardRef<IStreamTokenDialog>((_, ref) => {
    const [streamId, setStreamId] = useState('');
    const [duration, setDuration] = useState(3600);
    const [permissions, setPermissions] = useState<Record<StreamTokenPermission, boolean>>({
        subscribe: true,
        publish: false,
        admin: false
    });
    const [token, setToken] = useState('');
    const refDialog = useRef<HTMLDialogElement>(null);
    const refTokenResult = useRef<HTMLInputElement>(null);

    useImperativeHandle(ref, () => {
        return {
            show: (id: string) => {
                setStreamId(id);
                refDialog.current?.showModal();
            }
        };
    });

    const onConfirm = async (e: Event) => {
        e.preventDefault();
        const res = await createStreamToken({
            id: streamId,
            duration: duration,
            ...permissions
        });
        setToken(`${res.token_type} ${res.access_token}`);
    };

    useEffect(() => {
        if (token) {
            refTokenResult.current?.focus();
            refTokenResult.current?.select();
        }
    }, [token]);

    const onClose = (_e: Event) => {
        setToken('');
    };

    return (
        <Modal ref={refDialog} className="max-w-md" onClose={onClose}>
            <Modal.Header className="mb-2">
                <h3 className="font-bold">Create Token for stream {streamId}</h3>
            </Modal.Header>
            <Modal.Body>
                <label className="form-control">
                    <label className="label px-0">Duration:</label>
                    <label class="input input-bordered flex items-center gap-2">
                        <input
                            className="grow"
                            type="number"
                            value={duration} onInput={e => setDuration(e.currentTarget.valueAsNumber)}
                        />
                        <span>Seconds</span>
                    </label>
                </label>
                <label className="form-control mt-4">
                    <label className="label px-0 pb-0">Permissions:</label>
                    {Object.values(StreamTokenPermission).map(p =>
                        <label class="label justify-start gap-2">
                            <Checkbox
                                size="xs"
                                name={p}
                                checked={permissions[p]}
                                onChange={e => setPermissions({ ...permissions, [p]: e.currentTarget.checked })}
                            />
                            <span>{p}</span>
                        </label>
                    )}
                </label>
            </Modal.Body>
            <Modal.Actions>
                <form method="dialog" className="flex gap-2">
                    <Button onClick={onConfirm}>Confirm</Button>
                    <Button>Cancel</Button>
                </form>
            </Modal.Actions>
            {token ? (
                <label className="form-control">
                    <label className="label px-0">Token:</label>
                    <Input borderOffset type="text" value={token} ref={refTokenResult} />
                </label>
            ) : null}
        </Modal>
    );
});

// web/liveman/components/dialog-token.vue
<script lang="ts">
export interface IStreamTokenDialog {
    show(id: string): void;
}
</script>

<script setup lang="ts">
import { ref, useTemplateRef, watch } from "vue";

import { createStreamToken } from "../api";

enum StreamTokenPermission {
    Sub = "subscribe",
    Pub = "publish",
    Admin = "admin"
}

const streamTokenPermissions = Object.values(StreamTokenPermission);

const streamId = ref("");
const duration = ref(3600);
const permissions = ref<Record<StreamTokenPermission, boolean>>({
    subscribe: true,
    publish: false,
    admin: false
});
const token = ref("");
const dialogEl = useTemplateRef<HTMLDialogElement>("dialogEl");
const tokenResultEl = useTemplateRef<HTMLInputElement>("tokenResultEl");

const show = (id: string) => {
    streamId.value = id;
    dialogEl.value?.showModal();
};

defineExpose({ show });

const onConfirm = async () => {
    const res = await createStreamToken({
        id: streamId.value,
        duration: duration.value,
        ...permissions.value
    });
    token.value = `${res.token_type} ${res.access_token}`;
};

// the input mounts in the same render pass that set the token, so
// flush: "post" (Preact effects ran after render)
watch(token, (t) => {
    if (t) {
        tokenResultEl.value?.focus();
        tokenResultEl.value?.select();
    }
}, { flush: "post" });

const onClose = () => {
    token.value = "";
};
</script>

<template>
    <dialog ref="dialogEl" aria-label="Modal" aria-hidden="true" class="modal" @close="onClose">
        <div class="modal-box max-w-md">
            <div class="w-full text-xl mb-2">
                <h3 class="font-bold">Create Token for stream {{ streamId }}</h3>
            </div>
            <div>
                <label class="form-control">
                    <label class="label px-0">Duration:</label>
                    <label class="input input-bordered flex items-center gap-2">
                        <input
                            class="grow"
                            type="number"
                            :value="duration"
                            @input="duration = ($event.target as HTMLInputElement).valueAsNumber"
                        />
                        <span>Seconds</span>
                    </label>
                </label>
                <label class="form-control mt-4">
                    <label class="label px-0 pb-0">Permissions:</label>
                    <label v-for="p in streamTokenPermissions" :key="p" class="label justify-start gap-2">
                        <input
                            type="checkbox"
                            class="checkbox checkbox-xs"
                            :name="p"
                            :checked="permissions[p]"
                            @change="permissions = { ...permissions, [p]: ($event.target as HTMLInputElement).checked }"
                        />
                        <span>{{ p }}</span>
                    </label>
                </label>
            </div>
            <div class="modal-action">
                <form method="dialog" class="flex gap-2">
                    <button class="btn" @click.prevent="onConfirm">Confirm</button>
                    <button class="btn">Cancel</button>
                </form>
            </div>
            <label v-if="token" class="form-control">
                <label class="label px-0">Token:</label>
                <input ref="tokenResultEl" class="input input-bordered" type="text" :value="token" />
            </label>
        </div>
    </dialog>
</template>
