// web/liveman/components/nodes-table.vue
<script setup lang="ts">
import { watch } from "vue";
import { ArrowPathIcon, EllipsisHorizontalIcon } from "@heroicons/vue/24/outline";

import { useToken } from "@/shared/context";
import { useRefreshTimer } from "@/shared/hooks/use-refresh-timer";

import { type Node, getNodes } from "../api";

async function getNodesSorted(): Promise<Node[]> {
    try {
        const nodes = await getNodes();
        return nodes.sort((a, b) => a.alias.localeCompare(b.alias));
    } catch {
        return [];
    }
}

const { data: nodes, isRefreshing, updateData, toggleTimer } = useRefreshTimer<Node[]>([], getNodesSorted);
const token = useToken();

// refresh when the token changes; immediate matches the original Preact
// effect, which also ran once on mount (initial fetch)
watch(token, () => {
    void updateData();
}, { immediate: true });

function strategyEntries(strategy: Node["strategy"]): [string, string | number | boolean][] {
    return Object.entries(strategy ?? {});
}

function nodeUrl(alias: string): string {
    const urlObject = new URL(location.href);
    urlObject.searchParams.set("nodes", alias);
    return urlObject.toString();
}
</script>

<template>
    <div class="flex flex-wrap items-center gap-x-2 gap-y-1 px-4 py-2">
        <span class="font-bold text-lg">Nodes</span>
        <div aria-label="Badge" class="badge badge-ghost font-bold mr-auto">{{ nodes.length }}</div>
        <button class="btn btn-sm btn-ghost gap-2" @click="toggleTimer">
            Auto Refresh
            <input type="checkbox" class="checkbox checkbox-xs" :checked="isRefreshing" />
        </button>
        <button class="btn btn-sm btn-ghost gap-2" @click="updateData">
            Refresh
            <ArrowPathIcon class="size-4 stroke-current" />
        </button>
    </div>

    <div class="overflow-x-auto">
        <table class="table">
            <thead>
                <tr>
                    <th><span>Alias</span></th>
                    <td><span>Status</span></td>
                    <td><span>Delay</span></td>
                    <td><span>Strategy</span></td>
                    <td><span>API URL</span></td>
                </tr>
            </thead>
            <tbody>
                <tr v-for="n in nodes" :key="n.alias">
                    <th><span>{{ n.alias }}</span></th>
                    <td><span>{{ n.status }}</span></td>
                    <td><span>{{ n.duration }}</span></td>
                    <td>
                        <span v-if="strategyEntries(n.strategy).length <= 1" class="font-mono">
                            {{ strategyEntries(n.strategy)[0]?.join(" = ") ?? "-" }}
                        </span>
                        <div v-else class="dropdown dropdown-hover">
                            <label tabindex="0" class="font-mono flex items-center gap-1">
                                <span>{{ strategyEntries(n.strategy)[0].join(" = ") }}</span>
                                <EllipsisHorizontalIcon class="size-4" />
                            </label>
                            <ul tabindex="0" role="menu" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box z-10 mx-[-1rem]">
                                <table class="table table-xs">
                                    <tbody>
                                        <tr v-for="[k, v] in strategyEntries(n.strategy)" :key="k">
                                            <th><span class="text-sm font-mono">{{ k }}</span></th>
                                            <td><span class="text-sm font-mono">{{ v }}</span></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </ul>
                        </div>
                    </td>
                    <td>
                        <a class="link link-hover break-all" :href="nodeUrl(n.alias)" target="_blank">{{ nodeUrl(n.alias) }}</a>
                    </td>
                </tr>
                <tr v-if="nodes.length === 0">
                    <td colspan="5" class="text-center">N/A</td>
                </tr>
            </tbody>
        </table>
    </div>
</template>

// web/liveman/components/nodes-table.tsx
import { useContext, useEffect } from 'preact/hooks';

import { Badge, Button, Checkbox, Dropdown, Link, Table } from 'react-daisyui';
import { ArrowPathIcon, EllipsisHorizontalIcon } from '@heroicons/react/24/outline';

import { TokenContext } from '@/shared/context';
import { useRefreshTimer } from '@/shared/hooks/use-refresh-timer';

import { type Node, getNodes } from '../api';

async function getNodesSorted(): Promise<Node[]> {
    try {
        const nodes = await getNodes();
        return nodes.sort((a, b) => a.alias.localeCompare(b.alias));
    } catch {
        return [];
    }
}

export function NodesTable() {
    const nodes = useRefreshTimer([], getNodesSorted);
    const tokenContext = useContext(TokenContext);

    useEffect(() => {
        nodes.updateData();
    }, [tokenContext.token]);

    return (
        <>
            <div className="flex items-center gap-2 px-4 h-12">
                <span className="font-bold text-lg">Nodes</span>
                <Badge color="ghost" className="font-bold mr-auto">{nodes.data.length}</Badge>
                <Button
                    size="sm"
                    color="ghost"
                    endIcon={<Checkbox size="xs" checked={nodes.isRefreshing} />}
                    onClick={nodes.toggleTimer}
                >Auto Refresh</Button>
                <Button
                    size="sm"
                    color="ghost"
                    endIcon={<ArrowPathIcon className="size-4 stroke-current" />}
                    onClick={nodes.updateData}
                >Refresh</Button>
            </div>

            <Table className="overflow-x-auto">
                <Table.Head>
                    <span>Alias</span>
                    <span>Status</span>
                    <span>Delay</span>
                    <span>Strategy</span>
                    <span>API URL</span>
                </Table.Head>
                <Table.Body>
                    {nodes.data.length > 0 ? nodes.data.map(n =>
                        <Table.Row>
                            <span>{n.alias}</span>
                            <span>{n.status}</span>
                            <span>{n.duration}</span>
                            <NodeStrategyLabel strategy={n.strategy} />
                            <NodeLink node={n} />
                        </Table.Row>
                    ) : <tr><td colspan={5} className="text-center">N/A</td></tr>}
                </Table.Body>
            </Table>
        </>
    );
}

type NodeStrategyLabelProps = Pick<Node, 'strategy'>;

function NodeStrategyLabel({ strategy }: NodeStrategyLabelProps) {
    const entries = Object.entries(strategy ?? {});
    if (entries.length <= 1) {
        return <span className="font-mono">{entries[0]?.join(' = ') ?? '-'}</span>;
    }
    return (
        <Dropdown hover>
            <Dropdown.Toggle button={false} className="font-mono flex items-center gap-1">
                <span>{entries[0].join(' = ')}</span>
                <EllipsisHorizontalIcon className="size-4" />
            </Dropdown.Toggle>
            <Dropdown.Menu className="z-10 mx-[-1rem]">
                <Table size="xs">
                    <Table.Body>
                        {entries.map(([k, v]) =>
                            <Table.Row>
                                <span className="text-sm font-mono">{`${k}`}</span>
                                <span className="text-sm font-mono">{`${v}`}</span>
                            </Table.Row>
                        )}
                    </Table.Body>
                </Table>
            </Dropdown.Menu>
        </Dropdown>
    );
}

function NodeLink({ node }: { node: Node }) {
    const urlObject = new URL(location.href);
    urlObject.searchParams.set('nodes', node.alias);
    const url = urlObject.toString();
    return (
        <Link href={url} target="_blank">{url}</Link>
    );
}
