// web/shared/components/dialog-cascade.vue
<script lang="ts">
export interface ICascadeDialog {
    show(streamId: string): void;
}
</script>

<script setup lang="ts">
import { ref, useTemplateRef } from "vue";

import { cascade } from "../api";

interface Props {
    /** pull: create a stream sourced from a remote WHEP URL;
     * push: relay an existing stream to a remote WHIP URL. */
    mode: "pull" | "push";
}

const props = defineProps<Props>();

const streamId = ref("");
const cascadeURL = ref("");
const dialogEl = useTemplateRef<HTMLDialogElement>("dialogEl");

const show = (id: string) => {
    streamId.value = id;
    cascadeURL.value = props.mode === "pull"
        ? `${location.origin}/whep/`
        : `${location.origin}/whip/push`;
    dialogEl.value?.showModal();
};

defineExpose({ show });

const onConfirmCascadeURL = () => {
    if (cascadeURL.value === "") {
        return;
    }
    if (props.mode === "pull") {
        void cascade(streamId.value, { sourceUrl: cascadeURL.value });
    } else {
        void cascade(streamId.value, { targetUrl: cascadeURL.value });
    }
};
</script>

<template>
    <dialog ref="dialogEl" aria-label="Modal" aria-hidden="true" class="modal">
        <div class="modal-box max-w-md">
            <div class="w-full text-xl mb-2">
                <h3 v-if="mode === 'pull'" class="font-bold">Cascade Pull</h3>
                <h3 v-else class="font-bold">Cascade Push ({{ streamId }})</h3>
            </div>
            <div>
                <div v-if="mode === 'pull'" class="form-control">
                    <label class="label px-0">Stream ID:</label>
                    <input v-model="streamId" class="input input-bordered" />
                </div>
                <div class="form-control">
                    <label class="label px-0">{{ mode === "pull" ? "Source URL:" : "Target URL:" }}</label>
                    <input v-model="cascadeURL" class="input input-bordered" />
                </div>
            </div>
            <div class="modal-action">
                <form method="dialog" class="flex gap-2">
                    <button class="btn" @click="onConfirmCascadeURL">Confirm</button>
                    <button class="btn">Cancel</button>
                </form>
            </div>
        </div>
    </dialog>
</template>

// web/dialog-cascade.tsx
import { useState, useRef, useImperativeHandle } from 'preact/hooks'
import { forwardRef, TargetedEvent } from 'preact/compat';

import { cascade } from './api'

export interface ICascadeDialog {
    show(streamId: string): void
}

export const CascadePullDialog = forwardRef<ICascadeDialog>((_props, ref) => {
    const [cascadeURL, setCascadeURL] = useState('')
    const refDialog = useRef<HTMLDialogElement>(null)

    useImperativeHandle(ref, () => {
        return {
            show: (streamId: string) => {
                setCascadeURL("pull")
                if (refDialog.current) {
                    refDialog.current.onclose = () => {
                        const target = refDialog.current?.returnValue ?? ''
                        if (target !== '') {
                            cascade(target, {
                                src: location.href + "whep/" + streamId,
                            })
                        }
                    }
                    refDialog.current.showModal()
                }
            }
        }
    })

    const handleURLInputChange = (e: TargetedEvent<HTMLInputElement>) => {
        setCascadeURL(e.currentTarget.value)
    }

    return (
        <dialog ref={refDialog}>
            <form method="dialog">
                <h3>Cascade</h3>
                <p>
                    <label htmlFor="cascade-url">Stream Id:</label>
                    <br />
                    <input
                        type="text"
                        value={cascadeURL}
                        id="cascade-url"
                        className="min-w-sm"
                        onChange={handleURLInputChange}
                    />
                </p>
                <div>
                    <button value="">Cancel</button>
                    <button value={cascadeURL}>Confirm</button>
                </div>
            </form>
        </dialog>
    )
})

export const CascadePushDialog = forwardRef<ICascadeDialog>((_props, ref) => {
    const [cascadeURL, setCascadeURL] = useState('')
    const refDialog = useRef<HTMLDialogElement>(null)

    useImperativeHandle(ref, () => {
        return {
            show: (streamId: string) => {
                setCascadeURL(location.href + "whip/push")
                if (refDialog.current) {
                    refDialog.current.onclose = () => {
                        const target = refDialog.current?.returnValue ?? ''
                        if (target !== '') {
                            cascade(streamId, {
                                dst: target,
                            })
                        }
                    }
                    refDialog.current.showModal()
                }
            }
        }
    })

    const handleURLInputChange = (e: TargetedEvent<HTMLInputElement>) => {
        setCascadeURL(e.currentTarget.value)
    }

    return (
        <dialog ref={refDialog}>
            <form method="dialog">
                <h3>Cascade</h3>
                <p>
                    <label htmlFor="cascade-url">Target URL:</label>
                    <br />
                    <input
                        type="text"
                        value={cascadeURL}
                        id="cascade-url"
                        className="min-w-sm"
                        onChange={handleURLInputChange}
                    />
                </p>
                <div>
                    <button value="">Cancel</button>
                    <button value={cascadeURL}>Confirm</button>
                </div>
            </form>
        </dialog>
    )
})
